title: Math Notes
url: https://cossio.github.io

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag


disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: cossio-github-io